package guesswho;



import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author yiannis
 */
public class ChoosePerson extends javax.swing.JFrame {

    /**
     * Creates new form ChoosePerson
     */
    static Player p1;
    static Player p2;
    
    //an einai 0 pvp an einai 1 pvc
    int comp = 0;
    
    public ChoosePerson() {
        initComponents();
        jLabel2.setVisible(false);
        
        p1 = new Player();
        p2 = new Player();
        
         try {
    Image img1 = ImageIO.read(getClass().getResource("Tyler.png"));
    jButton1.setIcon(new ImageIcon(img1));
  } catch (Exception ex) {
    System.out.println(ex);
  }
              try {
    Image img2 = ImageIO.read(getClass().getResource("Joseph.png"));
    jButton2.setIcon(new ImageIcon(img2));
  } catch (Exception ex) {
    System.out.println(ex);
  }
               try {
    Image img3 = ImageIO.read(getClass().getResource("Nick.png"));
    jButton3.setIcon(new ImageIcon(img3));
  } catch (Exception ex) {
    System.out.println(ex);
  }
                try {
    Image img4 = ImageIO.read(getClass().getResource("Brandon.png"));
    jButton4.setIcon(new ImageIcon(img4));
  } catch (Exception ex) {
    System.out.println(ex);
  }
                 try {
    Image img5 = ImageIO.read(getClass().getResource("Connor.png"));
    jButton5.setIcon(new ImageIcon(img5));
  } catch (Exception ex) {
    System.out.println(ex);
  }   
                 try {
    Image img6 = ImageIO.read(getClass().getResource("Kyle.png"));
    jButton6.setIcon(new ImageIcon(img6));
  } catch (Exception ex) {
    System.out.println(ex);
  }             
                   
    }
    
    public ChoosePerson(int deyteros) {
        initComponents();
        jLabel1.setVisible(false);
        
         try {
    Image img1 = ImageIO.read(getClass().getResource("Tyler.png"));
    jButton1.setIcon(new ImageIcon(img1));
  } catch (Exception ex) {
    System.out.println(ex);
  }
              try {
    Image img2 = ImageIO.read(getClass().getResource("Joseph.png"));
    jButton2.setIcon(new ImageIcon(img2));
  } catch (Exception ex) {
    System.out.println(ex);
  }
               try {
    Image img3 = ImageIO.read(getClass().getResource("Nick.png"));
    jButton3.setIcon(new ImageIcon(img3));
  } catch (Exception ex) {
    System.out.println(ex);
  }
                try {
    Image img4 = ImageIO.read(getClass().getResource("Brandon.png"));
    jButton4.setIcon(new ImageIcon(img4));
  } catch (Exception ex) {
    System.out.println(ex);
  }
                 try {
    Image img5 = ImageIO.read(getClass().getResource("Connor.png"));
    jButton5.setIcon(new ImageIcon(img5));
  } catch (Exception ex) {
    System.out.println(ex);
  }   
                 try {
    Image img6 = ImageIO.read(getClass().getResource("Kyle.png"));
    jButton6.setIcon(new ImageIcon(img6));
  } catch (Exception ex) {
    System.out.println(ex);
  }         
    }
    //const gia player vs comp
    public ChoosePerson(String c) {
        initComponents();
        comp = 1;
        p1 = new Player();
        //player tou comp
        p2 = new Player(2);
        
        jLabel1.setVisible(false);
        
         try {
    Image img1 = ImageIO.read(getClass().getResource("Tyler.png"));
    jButton1.setIcon(new ImageIcon(img1));
  } catch (Exception ex) {
    System.out.println(ex);
  }
              try {
    Image img2 = ImageIO.read(getClass().getResource("Joseph.png"));
    jButton2.setIcon(new ImageIcon(img2));
  } catch (Exception ex) {
    System.out.println(ex);
  }
               try {
    Image img3 = ImageIO.read(getClass().getResource("Nick.png"));
    jButton3.setIcon(new ImageIcon(img3));
  } catch (Exception ex) {
    System.out.println(ex);
  }
                try {
    Image img4 = ImageIO.read(getClass().getResource("Brandon.png"));
    jButton4.setIcon(new ImageIcon(img4));
  } catch (Exception ex) {
    System.out.println(ex);
  }
                 try {
    Image img5 = ImageIO.read(getClass().getResource("Connor.png"));
    jButton5.setIcon(new ImageIcon(img5));
  } catch (Exception ex) {
    System.out.println(ex);
  }   
                 try {
    Image img6 = ImageIO.read(getClass().getResource("Kyle.png"));
    jButton6.setIcon(new ImageIcon(img6));
  } catch (Exception ex) {
    System.out.println(ex);
  }         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1600, 1000));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Player1 Choose Person:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Player2 Choose Person:");

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(389, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (comp==0) { 
        if (p1.getPlayerToBeFound() == -1) {
            p1.setPlayerToBeFound(0);
            this.dispose();
            ChoosePerson cp1 = new ChoosePerson(2);
            cp1.setVisible(true);
            System.out.println("player chose " + p1.getPlayerToBeFound());
        } else {
            p2.setPlayerToBeFound(0);
            this.dispose();
            Questions q = new Questions(1,p1,p2);
            q.setVisible(true);
            q.setResizable(false);
            System.out.println("player chose " + p2.getPlayerToBeFound());
        }
        } else if (comp==1) {
            p1.setPlayerToBeFound(0);
            int chosenPerson = (int) (Math.random()*6);
            p2.setPlayerToBeFound(chosenPerson);
            System.out.println("player1 chose " + p1.getPlayerToBeFound());
            System.out.println("player2 chose " + p2.getPlayerToBeFound());
            this.dispose();
            QuestionsWithComp qwc = new QuestionsWithComp(p1,p2);
            qwc.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (comp==0) { 
         if (p1.getPlayerToBeFound() == -1) {
            p1.setPlayerToBeFound(1);
            this.dispose();
            ChoosePerson cp1 = new ChoosePerson(2);
            cp1.setVisible(true);
            System.out.println("player chose " + p1.getPlayerToBeFound());
        } else {
            p2.setPlayerToBeFound(1);
            this.dispose();
            Questions q = new Questions(1,p1,p2);
            q.setVisible(true);
            q.setResizable(false);
            System.out.println("player chose " + p2.getPlayerToBeFound());
        }
        } else if (comp==1) {
            p1.setPlayerToBeFound(1);
            int chosenPerson = (int) (Math.random()*6);
            p2.setPlayerToBeFound(chosenPerson);
            System.out.println("player1 chose " + p1.getPlayerToBeFound());
            System.out.println("player2 chose " + p2.getPlayerToBeFound());
            this.dispose();
            QuestionsWithComp qwc = new QuestionsWithComp(p1,p2);
            qwc.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (comp==0) {
         if (p1.getPlayerToBeFound() == -1) {
            p1.setPlayerToBeFound(2);
            this.dispose();
            ChoosePerson cp1 = new ChoosePerson(2);
            cp1.setVisible(true);
            System.out.println("player chose " + p1.getPlayerToBeFound());
        } else {
            p2.setPlayerToBeFound(2);
            this.dispose();
            Questions q = new Questions(1,p1,p2);
            q.setVisible(true);
            q.setResizable(false);
            System.out.println("player chose " + p2.getPlayerToBeFound());
        }
        } else if (comp==1) { 
            p1.setPlayerToBeFound(2);
            int chosenPerson = (int) (Math.random()*6);
            p2.setPlayerToBeFound(chosenPerson);
            System.out.println("player1 chose " + p1.getPlayerToBeFound());
            System.out.println("player2 chose " + p2.getPlayerToBeFound());
            this.dispose();
            QuestionsWithComp qwc = new QuestionsWithComp(p1,p2);
            qwc.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (comp==0) {
        if (p1.getPlayerToBeFound() == -1) {
            p1.setPlayerToBeFound(3);
            this.dispose();
            ChoosePerson cp1 = new ChoosePerson(2);
            cp1.setVisible(true);
            System.out.println("player chose " + p1.getPlayerToBeFound());
        } else {
            p2.setPlayerToBeFound(3);
            this.dispose();
            Questions q = new Questions(1,p1,p2);
            q.setVisible(true);
            q.setResizable(false);
            System.out.println("player chose " + p2.getPlayerToBeFound());
        }
        } else if (comp==1) {
            p1.setPlayerToBeFound(3);
            int chosenPerson = (int) (Math.random()*6);
            p2.setPlayerToBeFound(chosenPerson);
            System.out.println("player1 chose " + p1.getPlayerToBeFound());
            System.out.println("player2 chose " + p2.getPlayerToBeFound());
            this.dispose();
            QuestionsWithComp qwc = new QuestionsWithComp(p1,p2);
            qwc.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (comp==0) {
        if (p1.getPlayerToBeFound() == -1) {
            p1.setPlayerToBeFound(4);
            this.dispose();
            ChoosePerson cp1 = new ChoosePerson(2);
            cp1.setVisible(true);
            System.out.println("player chose " + p1.getPlayerToBeFound());
        } else {
            p2.setPlayerToBeFound(4);
            this.dispose();
            Questions q = new Questions(1,p1,p2);
            q.setVisible(true);
            q.setResizable(false);
            System.out.println("player chose " + p2.getPlayerToBeFound());
        }
        } else if (comp==1) {
            p1.setPlayerToBeFound(4);
            int chosenPerson = (int) (Math.random()*6);
            p2.setPlayerToBeFound(chosenPerson);
            System.out.println("player1 chose " + p1.getPlayerToBeFound());
            System.out.println("player2 chose " + p2.getPlayerToBeFound());
            this.dispose();
            QuestionsWithComp qwc = new QuestionsWithComp(p1,p2);
            qwc.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (comp==0) {
        if (p1.getPlayerToBeFound() == -1) {
            p1.setPlayerToBeFound(5);
            this.dispose();
            ChoosePerson cp1 = new ChoosePerson(2);
            cp1.setVisible(true);
            System.out.println("player chose " + p1.getPlayerToBeFound());
        } else {
            p2.setPlayerToBeFound(5);
            this.dispose();
            Questions q = new Questions(1,p1,p2);
            q.setVisible(true);
            q.setResizable(false);
            System.out.println("player chose " + p2.getPlayerToBeFound());
        }
        } else if (comp==1) {
            p1.setPlayerToBeFound(5);
            int chosenPerson = (int) (Math.random()*6);
            p2.setPlayerToBeFound(chosenPerson);
            System.out.println("player1 chose " + p1.getPlayerToBeFound());
            System.out.println("player2 chose " + p2.getPlayerToBeFound());
            this.dispose();
            QuestionsWithComp qwc = new QuestionsWithComp(p1,p2);
            qwc.setVisible(true);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoosePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoosePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoosePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoosePerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoosePerson().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
