/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guesswho;

import java.awt.Image;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author yiannis
 */
public class FindingBoard extends javax.swing.JFrame {
    
    Player p;
    int seira;

    /**
     * Creates new form FindingBoard
     */
    public FindingBoard() {
        initComponents();
        
    }
    public FindingBoard(Player p, int s ) {
        initComponents();
        if (s == 1) {
            jLabel2.setVisible(false);
        } else {
            jLabel1.setVisible(false);
        }
        
        this.p = p;
        seira=s;
        
             try {
    Image img1 = ImageIO.read(getClass().getResource("Tyler.png"));
    jButton1.setIcon(new ImageIcon(img1));
  } catch (Exception ex) {
    System.out.println(ex);
  }
              try {
    Image img2 = ImageIO.read(getClass().getResource("Joseph.png"));
    jButton2.setIcon(new ImageIcon(img2));
  } catch (Exception ex) {
    System.out.println(ex);
  }
               try {
    Image img3 = ImageIO.read(getClass().getResource("Nick.png"));
    jButton3.setIcon(new ImageIcon(img3));
  } catch (Exception ex) {
    System.out.println(ex);
  }
                try {
    Image img4 = ImageIO.read(getClass().getResource("Brandon.png"));
    jButton4.setIcon(new ImageIcon(img4));
  } catch (Exception ex) {
    System.out.println(ex);
  }
                 try {
    Image img5 = ImageIO.read(getClass().getResource("Connor.png"));
    jButton5.setIcon(new ImageIcon(img5));
  } catch (Exception ex) {
    System.out.println(ex);
  }   
                 try {
    Image img6 = ImageIO.read(getClass().getResource("Kyle.png"));
    jButton6.setIcon(new ImageIcon(img6));
  } catch (Exception ex) {
    System.out.println(ex);
  }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 700));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Player1 tries to find:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Player2 tries to find:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)))
                .addContainerGap(531, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(467, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
            if (p.getPlayerToBeFound()==0) {
                JOptionPane.showMessageDialog(null, "Player wins!! found the wanted person!! it's Tyler");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Player lost.. the wanted person is " + getRightPerson(p.getPlayerToBeFound()));
                this.dispose();
            } 
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (p.getPlayerToBeFound()==1) {
                JOptionPane.showMessageDialog(null, "Player wins!! found the wanted person!! it's Joseph");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Player lost.. the wanted person is " + getRightPerson(p.getPlayerToBeFound()));
                this.dispose();
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (p.getPlayerToBeFound()==2) {
                JOptionPane.showMessageDialog(null, "Player wins!! found the wanted person!! it's Nick");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Player lost.. the wanted person is " + getRightPerson(p.getPlayerToBeFound()));
                this.dispose();
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (p.getPlayerToBeFound()==3) {
                JOptionPane.showMessageDialog(null, "Player wins!! found the wanted person!! it's Brandon");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Player lost.. the wanted person is " + getRightPerson(p.getPlayerToBeFound()));
                this.dispose();
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (p.getPlayerToBeFound()==4) {
                JOptionPane.showMessageDialog(null, "Player wins!! found the wanted person!! it's Connor");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Player lost.. the wanted person is " + getRightPerson(p.getPlayerToBeFound()));
                this.dispose();
            }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (p.getPlayerToBeFound()==5) {
                JOptionPane.showMessageDialog(null, "Player wins!! found the wanted person!! it's Kyle");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Player lost.. the wanted person is " + getRightPerson(p.getPlayerToBeFound()));
                this.dispose();
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    public String getRightPerson(int n) {
        String name = null;
        if (n==0) {
            name = "Tyler";
        } else if (n==1) {
            name = "Joseph";
        } else if (n==2) {
            name = "Nick";
        } else if (n==3) {
            name = "Brandon";
        } else if (n==4) {
            name = "Connor";
        } else if (n==5) {
            name = "Kyle";
        }
        return name;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindingBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindingBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindingBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindingBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindingBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
